.TH "include/ Directory Reference" 3 "4 May 2005" "Version 2.05-dev" "libapreq2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ Directory Reference \- 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBapreq.h\fP"
.br
.RI "\fIMain header file... \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBapreq_cookie.h\fP"
.br
.RI "\fICookies and Jars. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBapreq_error.h\fP"
.br
.RI "\fIError status codes. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBapreq_module.h\fP"
.br
.RI "\fIModule API. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBapreq_param.h\fP"
.br
.RI "\fIRequest parsing and parameter API. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBapreq_parser.h\fP"
.br
.RI "\fIRequest body parser API. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBapreq_util.h\fP"
.br
.RI "\fIUtility functions for apreq. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBapreq_version.h\fP"
.br
.RI "\fIVersioning API for libapreq. \fP"
.PP

.in -1c
