.TH "Perl" 3 "4 May 2005" "Version 2.05-dev" "libapreq2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Perl \- XS Modules.  

.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBApache2::Request\fP"
.br
.ti -1c
.RI "\fBApache2::Upload\fP"
.br
.ti -1c
.RI "\fBApache2::Cookie\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
XS Modules. 
.PP
 
.SH "SEE ALSO"
.IX Header "SEE ALSO"
\&\fIapreq_xs_request\fR\|(3), \fIapreq_xs_upload\fR\|(3), \fIapreq_xs_cookie\fR\|(3)
 
