.TH "apreq_param_t" 3 "4 May 2005" "Version 2.05-dev" "libapreq2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apreq_param_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <apreq_param.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBapr_table_t\fP * \fBinfo\fP"
.br
.ti -1c
.RI "\fBapr_bucket_brigade\fP * \fBupload\fP"
.br
.ti -1c
.RI "unsigned \fBflags\fP"
.br
.ti -1c
.RI "const \fBapreq_value_t\fP \fBv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Common data structure for params and file uploads 
.PP
.SH "Field Documentation"
.PP 
.SS "unsigned \fBapreq_param_t::flags\fP"
.PP
charsets, taint marks, app-specific bits 
.SS "\fBapr_table_t\fP* \fBapreq_param_t::info\fP"
.PP
header table associated with the param 
.SS "\fBapr_bucket_brigade\fP* \fBapreq_param_t::upload\fP"
.PP
brigade used to spool upload files 
.SS "const \fBapreq_value_t\fP \fBapreq_param_t::v\fP"
.PP
underlying name/value info 

.SH "Author"
.PP 
Generated automatically by Doxygen for libapreq2 from the source code.
