.TH "Modules" 3 "4 May 2005" "Version 2.05-dev" "libapreq2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Modules \- apreq2 modules included in libapreq2-2.05-dev.  

.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBApache 2.X Filter Module\fP"
.br
.RI "\fImod_apreq2 - DSO that ties libapreq2 to \fBApache\fP HTTPD 2.X. \fP"
.PP

.in -1c
.SH "Detailed Description"
.PP 
apreq2 modules included in libapreq2-2.05-dev. 
.PP
XXX 
