.TH "apreq_parser_t" 3 "4 May 2005" "Version 2.05-dev" "libapreq2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apreq_parser_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <apreq_parser.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBapreq_parser_function_t\fP \fBparser\fP"
.br
.ti -1c
.RI "const char * \fBcontent_type\fP"
.br
.ti -1c
.RI "\fBapr_pool_t\fP * \fBpool\fP"
.br
.ti -1c
.RI "\fBapr_bucket_alloc_t\fP * \fBbucket_alloc\fP"
.br
.ti -1c
.RI "\fBapr_size_t\fP \fBbrigade_limit\fP"
.br
.ti -1c
.RI "const char * \fBtemp_dir\fP"
.br
.ti -1c
.RI "\fBapreq_hook_t\fP * \fBhook\fP"
.br
.ti -1c
.RI "void * \fBctx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A request body parser instance. 
.PP
.SH "Field Documentation"
.PP 
.SS "\fBapr_size_t\fP \fBapreq_parser_t::brigade_limit\fP"
.PP
the maximum in-memory bytes a brigade may use 
.SS "\fBapr_bucket_alloc_t\fP* \fBapreq_parser_t::bucket_alloc\fP"
.PP
bucket allocator used to create bucket brigades 
.SS "const char* \fBapreq_parser_t::content_type\fP"
.PP
the Content-Type request header 
.SS "void* \fBapreq_parser_t::ctx\fP"
.PP
internal context pointer used by the parser function 
.SS "\fBapreq_hook_t\fP* \fBapreq_parser_t::hook\fP"
.PP
linked list of hooks 
.SS "\fBapreq_parser_function_t\fP \fBapreq_parser_t::parser\fP"
.PP
the function which parses chunks of body data 
.SS "\fBapr_pool_t\fP* \fBapreq_parser_t::pool\fP"
.PP
a pool used by the parser 
.SS "const char* \fBapreq_parser_t::temp_dir\fP"
.PP
the directory used by the parser for temporary files 

.SH "Author"
.PP 
Generated automatically by Doxygen for libapreq2 from the source code.
