.TH "Apache Request Library" 3 "4 May 2005" "Version 2.05-dev" "libapreq2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Apache Request Library \- libapreq2 Version 2.1.0  

.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBapreq.h\fP"
.br
.RI "\fIMain header file... \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBapreq_cookie.h\fP"
.br
.RI "\fICookies and Jars. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBapreq_error.h\fP"
.br
.RI "\fIError status codes. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBapreq_module.h\fP"
.br
.RI "\fIModule API. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBapreq_param.h\fP"
.br
.RI "\fIRequest parsing and parameter API. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBapreq_parser.h\fP"
.br
.RI "\fIRequest body parser API. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBapreq_util.h\fP"
.br
.RI "\fIUtility functions for apreq. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBapreq_version.h\fP"
.br
.RI "\fIVersioning API for libapreq. \fP"
.PP

.in -1c
.SH "Detailed Description"
.PP 
libapreq2 Version 2.1.0 
.PP
libapreq2 is a shared library based on the \fBApache\fP Portable Runtime libraries libapr and libaprutil. 
.PP
\fBSee also:\fP
.RS 4
http://apr.apache.org/
.RE
.PP
.SH "Configuring libapreq2 Applications"
.PP
This package includes \fCapreq2-config\fP, a configuration script for building applications with libapreq2. Run \fCapreq2-config --help\fP to display its options. XXX add examples here XXX 
