.TH "todo" 3 "4 May 2005" "Version 2.05-dev" "libapreq2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List
 
.IP "\fBGlobal \fBAPREQ_COOKIE_MAX_LENGTH\fP \fP" 1c
convert this macro to an \fBapreq_module_t\fP method.
.PP
.PP
 
.IP "\fBGlobal \fBapreq_atoi64f\fP(const char *s) \fP" 1c
What happens when s is malformed? Should this return an unsigned value instead? 
.PP
.PP
 
.IP "\fBGlobal \fBapreq_atoi64t\fP(const char *s) \fP" 1c
What happens when s is malformed? Should this return an unsigned value instead? 
.PP
.PP
 
.IP "\fBGlobal \fBapreq_brigade_concat\fP(apr_pool_t *pool, const char *temp_dir, apr_size_t brigade_limit, \fBapr_bucket_brigade\fP *out, \fBapr_bucket_brigade\fP *in) \fP" 1c
Flesh out these error codes, making them as explicit as possible. 
.PP

